[package]
name = "evreos-shell"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
evreos-engine = { path = "../evreos-engine" }
evreos-engine-headless = { path = "../evreos-engine-headless" }

[lints]
workspace = true
