#!/usr/bin/env python3
"""Check commit authorship and signatures, and block automated AI-attribution
artifacts.

WHAT THIS CHECKS, and why the scope is narrow.

The real, recurring problem is mechanical: tooling appends a fixed footer or a
`Co-Authored-By:` trailer to a commit message or a pull request body. Those are
literal strings in known shapes, so they can be detected exactly.

An earlier version of this script also tried to detect attribution written as
free English ("assisted by X", "X's implementation"). Three rounds of adversarial
review showed that is not tractable for a browser project: `cursor` is everyday
vocabulary ("the text cursor is created before layout"), an AI sidebar is a
product feature, and a bare https://platform.openai.com/... URL parses as a
trailer. Each pattern that caught more phrasings also rejected more legitimate
commits. Blocking a real commit is worse than missing prose no tool emits, so
prose detection was removed.

Free-prose attribution remains forbidden by Principle I of the constitution.
It is enforced by review, not by this script, and this script does not pretend
otherwise.

CHECKED (deterministic, but neither half is free of false positives — see
the known defects below):
  * commit author is the founder; committer is the founder or the forge
  * a git trailer in the trailing trailer block whose value names an AI identity
  * a literal generator footer, matched even inside code fences
  * Conventional Commits subject, and an issue reference
  * with --allowed-signers-file: every commit in the range carries an SSH
    signature that verifies against a key in that file, under the founder's
    address as principal

SIGNATURES. Principle I requires every commit to be signed. The trust root is
an OpenSSH allowed_signers file, `.github/allowed-signers` in this repository,
and verification is git's own (`gpg.ssh.allowedSignersFile`, which runs
`ssh-keygen -Y`). Three properties of the check are deliberate:

  * A file with no key entry means signing is not yet enabled. The check says
    so and skips, rather than failing every commit, so the mechanism can land
    before the founder adds a key without breaking every pull request. A file
    that does not exist, by contrast, is an error: a typo in the flag must not
    silently turn enforcement off.
  * The CI workflow hands this script the copy of the file on the BASE branch,
    not the one in the pull request. A pull request that could add its own key
    would authorise its own signatures. A key therefore takes effect one merge
    after it lands, and the pull request that adds the first key is checked
    against no key at all — the not-yet-enabled case above.
  * The check sees `origin/<base>..HEAD`, which never contains the merge commit
    the forge creates when the pull request lands; that commit does not exist
    yet. So this gates the branch, and only branch protection gates `main`.
    The required settings are recorded in docs/governance/branch-protection.md.

KNOWN DEFECTS, both tracked as issue #25. Note #26 tracks the inverse of the
second one: a co-authorship trailer naming a human currently passes.

First, the generator-footer strings are matched against the whole normalised
text rather than a trailer block, so they fire on ordinary prose containing
"generated with"/"generated by" followed by a tool name. A sentence naming a
tool this project integrates with — which Principle I's carve-out expressly
permits — is rejected, and so is a layout sentence like "the caret rect is
generated by cursor metrics".

Second, the trailer identities are bare given names, and the trailer rule reads
any key whose suffix is the exact lowercase -by or -with. A legitimate
Reviewed-by or Reported-by trailer naming a human called Claude or Devin is
rejected, although CLAUDE.md bans only co-authorship trailers and Principle I
expressly permits recording that a review ran. The key match is case-sensitive,
so the canonical Co-Authored-By and Reviewed-By spellings are invisible to this
rule; such a trailer is caught only if its own text hits the footer list.
"""
import argparse
import os
import re
import shutil
import subprocess
import sys
import unicodedata

# The canonical founder identity, named in error messages and in CLAUDE.md.
REQUIRED_AUTHOR = "xcoder-es <capintobe@gmail.com>"
# The address alone identifies the founder; it is also the principal every
# entry in the allowed-signers file carries, which ties a signing key to the
# same identity the author check requires.
FOUNDER_EMAIL = "capintobe@gmail.com"
# The founder writes under two display names on one address. The address is what
# identifies them; the display name is presentation, and a forge stamps whichever
# one the account carries onto the merge commits it creates. Both are the founder,
# recorded as a founder decision on 2026-08-30. This is not a widening: an author
# at any other address still fails, which is the property Principle I needs.
FOUNDER_AUTHORS = {REQUIRED_AUTHOR, f"Carlos Pinto <{FOUNDER_EMAIL}>"}
# A forge is the committer of the merge commits it creates. That is infrastructure.
ALLOWED_COMMITTERS = FOUNDER_AUTHORS | {"GitHub <noreply@github.com>"}

# Identities, tested ONLY against a git trailer's value, where "Claude
# <noreply@anthropic.com>" is unambiguous. Never tested against prose.
#
# The list matches CANONICAL_FOOTER's. They named different tools once --
# `cursor` and `codex` were in the footer list and not here -- so a trailer
# naming one of the two passed a check that rejected the same tool in a footer.
TRAILER_IDENTITY = re.compile(
    r"anthropic\.com|\bclaude\b|\bcopilot\b|\bchatgpt\b|\bgithub-actions\[bot\]\b"
    r"|\bopenai\b|\bgemini\b|\bdevin\b|\bcodex\b|\bcursor\s+(?:agent|ai|bot)\b"
    r"|\bcursor\b(?=\s*<)",
    re.IGNORECASE,
)

# A git trailer line: a token key, a colon, a value. Keys never contain spaces,
# which is what separates "Co-Authored-By: x" from "Note: some sentence".
#
# IGNORECASE is load-bearing. Without it the `-by` alternative matched only the
# lowercase spelling, so `Co-Authored-By:` -- the capitalisation git itself
# writes and every tool emits -- never reached the identity test at all.
# A leading `>` or `-` is stripped before matching, so a trailer quoted in a
# pull request body or listed as a bullet is still read as one. Anchoring the
# footer branch to the line start was right -- prose quotes a trailer
# mid-sentence -- but a blockquote renders as visibly as a code fence, and the
# fenced form is already a must-fail here.
TRAILER_MARKER = re.compile(r"^[>\-*+\s]*")
# What a trailer's value carries when the line is quoted or bulleted: an
# address, somewhere in it. Prose does not.
#
# SEARCHED, not matched end to end. Anchoring the whole value meant a trailing
# full stop, a parenthetical after the address, a second co-author on the same
# line, or a name with no address at all all failed the test -- and a failed
# test skips the line, so a genuine attribution passed. A trailer decorated in
# any of those ways is still a trailer.
IDENTITY_VALUE = re.compile(r"<[^<>@\s]+@[^<>\s]+>|(?:^|\s)[^<>@\s]+@[^<>\s]+")
TRAILER_LINE = re.compile(
    r"^(?P<key>[A-Za-z][A-Za-z-]*-(?:by|with)):[ \t]*(?P<value>.+?)[ \t]*$",
    re.IGNORECASE,
)

# CLAUDE.md's Authorship section bans co-authorship trailers OUTRIGHT, naming a
# human included, because sole authorship is the point: "NO `Co-Authored-By`
# trailer of any kind". That is stricter than Principle I, which reaches only
# attribution to an AI or generator tool, and the file states the narrowing
# deliberately. It was previously a review obligation with nothing enforcing
# it, which is how a `Co-Authored-By: GitHub Copilot <...>` trailer passed: the
# identity list held `copilot`, but the key never matched to be tested against
# it, and the footer pattern anchored the tool name immediately after the
# colon, so any display name in front of it defeated the match.
CO_AUTHORSHIP_KEY = re.compile(r"^co-authored-by$", re.IGNORECASE)
# The key group captures the whole key including its `-by`/`-with` suffix. It
# once stopped short of the suffix, so the key of `Co-Authored-By:` read
# `Co-Authored` and matched no rule keyed on the full name.

# Literal footers that tooling emits. Matched anywhere, including inside code
# fences, because a fence still renders as a visible attribution.
CANONICAL_FOOTER = re.compile(
    r"🤖\s*generated"
    r"|generated\s+(?:with|by)\s+\[?(?:claude|copilot|chatgpt|codex|cursor|gemini|devin)\b"
    r"|noreply@anthropic\.com"
    # Anchored to the start of a line: a co-authorship TRAILER begins one, and
    # prose describing the rule quotes it mid-sentence. Unanchored, this branch
    # rejected a commit message explaining what the check refuses -- exactly the
    # over-reach CLAUDE.md records as issue #25, where "a plainly descriptive
    # sentence naming a tool this project does integrate with" is rejected
    # though Principle I's carve-out permits it. A real trailer is still caught
    # here, and CO_AUTHORSHIP_KEY catches every one of them again by key,
    # whoever it names, so nothing rests on this branch alone.
    r"|(?m:^co-authored-by:)[^\n]*?(?:claude|copilot|chatgpt|codex|cursor|gemini|devin)\b",
    re.IGNORECASE,
)

CONVENTIONAL = re.compile(
    r"^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)"
    r"(\([a-z0-9._/-]+\))?!?: [a-z].*"
)
# A linking keyword is required; a bare #NNN also matches CSS colours and URL
# fragments.
ISSUE_REF = re.compile(
    r"\b(closes?|fixes|fixed|resolves?|refs?|see)\s+#\d+\b", re.IGNORECASE
)
# Messages a forge or git writes itself, exempt from subject and issue rules.
GENERATED_SUBJECT = re.compile(r"^(Merge |Revert \"|fixup! |squash! )")

CODE_SPAN_OR_BLOCK = re.compile(r"```.*?```|`[^`\n]*`", re.DOTALL)

# The armour git wraps each signature format in, inside the commit object's
# gpgsig header. Read from the object rather than inferred from verification
# output, because only an SSH signature can be checked against the file at all.
SIGNATURE_ARMOUR = {
    "-----BEGIN SSH SIGNATURE-----": "ssh",
    "-----BEGIN PGP SIGNATURE-----": "openpgp",
    "-----BEGIN SIGNED MESSAGE-----": "x509",
}
# A public key type, which begins an OpenSSH public-key line but must NOT begin
# an allowed_signers entry: the entry starts with the principal. Pasting a
# .pub line unchanged is the likely mistake, and it would make every signature
# fail with a message about a missing principal rather than about the file.
KEY_TYPE_PREFIX = ("ssh-", "ecdsa-sha2-", "sk-")
# What git's %G? reports when a signature does not verify, in words. Only "G"
# passes; every other value is a failure and gets its reason from here.
SIGNATURE_STATUS = {
    "U": "the signing key is not in the allowed-signers file",
    "B": "the signature is bad: the commit was altered after signing",
    "E": "the signature cannot be checked",
    "X": "the signature has expired",
    "Y": "the signing key has expired",
    "R": "the signing key has been revoked",
    "N": "the commit is not signed",
}


def normalise(text):
    """Fold unicode tricks: compatibility forms, then all invisible formatting."""
    folded = unicodedata.normalize("NFKC", text)
    return "".join(
        ch for ch in folded
        if unicodedata.category(ch) != "Cf" and ch not in "­͏"
    )


def trailer_block(text):
    """The trailing paragraph, which is where git puts trailers."""
    paragraphs = [p for p in re.split(r"\n\s*\n", text.strip()) if p.strip()]
    return paragraphs[-1] if paragraphs else ""


def attribution_problems(text, where):
    """Return attribution problems as description strings."""
    full = normalise(text)
    found = []
    if CANONICAL_FOOTER.search(full):
        found.append(f"{where}: carries a generator footer or AI attribution trailer")
    # Every trailer-shaped line in the whole message, not only the trailing
    # paragraph. A trailer above a later paragraph is still a trailer that
    # ships, and reading only the last paragraph is how one earlier in the
    # message went uninspected.
    for line in full.splitlines():
        stripped = TRAILER_MARKER.sub("", line)
        # A line beginning the key at column zero is a trailer by git's own
        # rules, whatever its value. Behind a `>` or a `-` it is a trailer only
        # if it carries an identity -- otherwise a bullet of prose ABOUT the
        # rule reads as a breach of it, which is the same over-reach anchoring
        # the footer branch was meant to end. A commit message describing this
        # very change was rejected by the unqualified form.
        # Compared against the line itself, not against `line.rstrip()`: those
        # strip opposite ends, so any line ending in whitespace read as marked
        # even with no marker on it -- and a column-zero trailer, which needs
        # no identity, was then skipped for want of one.
        marked = stripped != line
        match = TRAILER_LINE.match(stripped)
        if match and marked and not IDENTITY_VALUE.search(match.group("value")):
            continue
        if not match:
            continue
        key, value = match.group("key"), match.group("value")
        if CO_AUTHORSHIP_KEY.match(key):
            found.append(
                f"{where}: carries a {key!r} trailer naming {value!r}; this "
                f"repository allows no co-authorship trailer of any kind"
            )
        elif TRAILER_IDENTITY.search(value):
            found.append(
                f"{where}: trailer {key!r} attributes the work to {value!r}"
            )
    return found


def run(*args):
    return subprocess.run(["git", *args], capture_output=True, text=True, check=True).stdout


def check_message(message, where, problems):
    problems.extend(attribution_problems(message, where))
    lines = message.strip().splitlines()
    subject = lines[0] if lines else ""
    if GENERATED_SUBJECT.match(subject):
        return
    if not CONVENTIONAL.match(subject):
        problems.append(
            f"{where}: subject is not a Conventional Commit "
            "(type(scope): lowercase imperative subject)"
        )
    if not ISSUE_REF.search(CODE_SPAN_OR_BLOCK.sub(" ", normalise(message))):
        problems.append(
            f"{where}: does not reference an issue (e.g. 'Closes #12' or 'Refs #12')"
        )


def allowed_signer_entries(path):
    """The key entries in an allowed_signers file: every line that is neither
    blank nor a comment. Raises ValueError for an entry with no principal."""
    entries = []
    with open(path, encoding="utf-8") as handle:
        for number, line in enumerate(handle, 1):
            entry = line.strip()
            if not entry or entry.startswith("#"):
                continue
            if entry.startswith(KEY_TYPE_PREFIX):
                raise ValueError(
                    f"{path}:{number}: entry starts with a key type and so has no "
                    f"principal; the format is '{FOUNDER_EMAIL} ssh-ed25519 AAAA...'"
                )
            entries.append(entry)
    return entries


def signature_kind(sha):
    """'ssh', 'openpgp', 'x509', 'unknown', or None when the commit is unsigned.
    Read from the commit object's header, before the first blank line, so a
    message quoting a signature block cannot be mistaken for one."""
    header = run("cat-file", "commit", sha).split("\n\n", 1)[0]
    for armour, kind in SIGNATURE_ARMOUR.items():
        if armour in header:
            return kind
    if header.startswith("gpgsig ") or "\ngpgsig " in header:
        return "unknown"
    return None


def check_signature(sha, where, allowed_signers, problems):
    """Fail unless the commit carries an SSH signature that git verifies against
    `allowed_signers` under the founder's address as principal."""
    listed = f"the keys in {os.path.basename(allowed_signers)}"
    kind = signature_kind(sha)
    if kind is None:
        problems.append(
            f"{where}: is not signed; Principle I requires a signature by one of {listed}"
        )
        return
    if kind != "ssh":
        problems.append(
            f"{where}: carries an {kind} signature, which cannot be verified against "
            f"{listed}; sign with the SSH key listed there"
        )
        return
    # The verifier is named here so a global git configuration on the machine
    # running the check cannot substitute another program for it; it is the
    # ssh-keygen main() confirmed is on PATH.
    status, principal, fingerprint = run(
        "-c", f"gpg.ssh.allowedSignersFile={allowed_signers}",
        "-c", "gpg.ssh.program=ssh-keygen",
        "log", "-1", "--format=%G?%x00%GS%x00%GF", sha,
    ).rstrip("\n").split("\0")
    if status != "G":
        reason = SIGNATURE_STATUS.get(status, f"git reports signature status {status!r}")
        problems.append(
            f"{where}: signature by key {fingerprint or '(unknown)'} does not verify "
            f"against {listed}: {reason}"
        )
        return
    if principal != FOUNDER_EMAIL:
        problems.append(
            f"{where}: signature verifies for principal {principal!r}, "
            f"not the founder's address {FOUNDER_EMAIL!r}"
        )


def check_commit(sha, problems, allowed_signers=None):
    author = run("log", "-1", "--format=%an <%ae>", sha).strip()
    committer = run("log", "-1", "--format=%cn <%ce>", sha).strip()
    message = run("log", "-1", "--format=%B", sha)
    subject = message.splitlines()[0] if message.splitlines() else ""
    where = f"commit {sha[:8]} ({subject[:50]})"

    if author not in FOUNDER_AUTHORS:
        problems.append(f"{where}: author is {author!r}, must be {REQUIRED_AUTHOR!r}")
    if committer not in ALLOWED_COMMITTERS:
        problems.append(f"{where}: committer is {committer!r}, must be {REQUIRED_AUTHOR!r}")
    check_message(message, where, problems)
    if allowed_signers:
        check_signature(sha, where, allowed_signers, problems)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--range", help="git rev range to check, e.g. base..head")
    parser.add_argument("--pr-body", help="file holding the pull request body")
    parser.add_argument("--pr-title", help="file holding the pull request title")
    parser.add_argument("--commit-msg", help="file holding a commit message, for the hook")
    parser.add_argument(
        "--allowed-signers-file",
        help="OpenSSH allowed_signers file every commit in --range must verify "
        "against; a file with no key entry means signing is not yet enabled",
    )
    args = parser.parse_args()

    problems = []

    allowed_signers = None
    if args.allowed_signers_file:
        allowed_signers = os.path.abspath(args.allowed_signers_file)
        if not os.path.isfile(allowed_signers):
            print(f"Allowed-signers file {allowed_signers!r} does not exist.", file=sys.stderr)
            return 2
        try:
            entries = allowed_signer_entries(allowed_signers)
        except ValueError as error:
            print(f"Malformed allowed-signers file: {error}", file=sys.stderr)
            return 2
        if not entries:
            print(
                f"Signature check skipped: {args.allowed_signers_file} lists no key, so "
                "signing is not yet enabled. It is enabled by listing the founder's "
                "public key in .github/allowed-signers."
            )
            allowed_signers = None
        elif shutil.which("ssh-keygen") is None:
            print(
                "Cannot verify signatures: ssh-keygen is not on PATH, and git needs it "
                "to check an SSH signature.",
                file=sys.stderr,
            )
            return 2

    if args.range:
        try:
            shas = run("log", "--format=%H", args.range).split()
        except subprocess.CalledProcessError as error:
            print(
                f"Cannot resolve rev range {args.range!r}: "
                f"{(error.stderr or '').strip().splitlines()[0] if error.stderr else 'git error'}",
                file=sys.stderr,
            )
            return 2
        if not shas:
            print(f"No commits in {args.range}; nothing to check.")
        for sha in shas:
            check_commit(sha, problems, allowed_signers)
        if shas and allowed_signers:
            print(
                f"Verified {len(shas)} signature(s) against {args.allowed_signers_file}."
                if not problems else
                f"Checked {len(shas)} signature(s) against {args.allowed_signers_file}."
            )

    for path, label in ((args.pr_body, "pull request body"), (args.pr_title, "pull request title")):
        if path:
            with open(path, encoding="utf-8") as handle:
                problems.extend(attribution_problems(handle.read(), label))

    if args.commit_msg:
        with open(args.commit_msg, encoding="utf-8") as handle:
            raw = handle.read()
        body = "\n".join(
            line for line in raw.split("# ------------------------ >8")[0].splitlines()
            if not line.startswith("#")
        )
        check_message(body, "commit message", problems)

    if problems:
        print("Commit hygiene check FAILED:\n", file=sys.stderr)
        for problem in problems:
            print(f"  - {problem}", file=sys.stderr)
        print(
            "\nSee Principle I of .specify/memory/constitution.md, and the "
            "Authorship section of CLAUDE.md for what this script does and does not check.",
            file=sys.stderr,
        )
        return 1

    print("Commit hygiene check passed.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
