#!/usr/bin/env python3
"""Check commit authorship and the absence of AI attribution.

Reads commits from git and, when given --pr-body, the pull request body too.
Exits non-zero and prints every violation found.

The rule is about ATTRIBUTION, not vocabulary: naming a tool the project
integrates with (the .claude/ directory, Spec Kit's Claude Code integration)
is description and passes. Claiming a tool authored or assisted the work fails.
"""
import argparse
import re
import subprocess
import sys

REQUIRED_AUTHOR = "xcoder-es <capintobe@gmail.com>"

# Trailers that attribute authorship to another party.
TRAILER = re.compile(
    r"^\s*(co-authored-by|generated-by|assisted-by|created-by|signed-off-by-ai)\s*:",
    re.IGNORECASE | re.MULTILINE,
)

# Attribution phrasings. These target the CLAIM ("generated by X", "written by X",
# "with help from X"), not any mention of a tool's name.
ATTRIBUTION = re.compile(
    r"(generated|authored|written|created|produced|made)\s+(with|by|using)\s+"
    r"[^\n.]{0,40}?(claude|anthropic|copilot|chatgpt|gpt-?\d|gemini|cursor|codex|ai\b)"
    r"|(with|using)\s+(the\s+)?(help|assistance|aid)\s+of\s+[^\n.]{0,40}?"
    r"(claude|anthropic|copilot|chatgpt|gpt-?\d|gemini|ai\b)"
    r"|\bai[- ]?(generated|authored|assisted|written)\b"
    r"|\b(claude|copilot|chatgpt)\s+(wrote|generated|authored|created)\b"
    r"|🤖\s*generated",
    re.IGNORECASE,
)

CONVENTIONAL = re.compile(
    r"^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)"
    r"(\([a-z0-9._/-]+\))?!?: [a-z].*"
)

ISSUE_REF = re.compile(r"#\d+")


def run(*args):
    return subprocess.run(
        ["git", *args], capture_output=True, text=True, check=True
    ).stdout


def commits_in_range(rev_range):
    out = run("log", "--no-merges", "--format=%H", rev_range).split()
    return out


def check_commit(sha, problems):
    author = run("log", "-1", "--format=%an <%ae>", sha).strip()
    message = run("log", "-1", "--format=%B", sha)
    subject = message.splitlines()[0] if message.splitlines() else ""
    where = f"commit {sha[:8]} ({subject[:50]})"

    if author != REQUIRED_AUTHOR:
        problems.append(f"{where}: author is {author!r}, must be {REQUIRED_AUTHOR!r}")
    if TRAILER.search(message):
        problems.append(f"{where}: carries an attribution trailer")
    if ATTRIBUTION.search(message):
        problems.append(f"{where}: message attributes the work to an AI or generator tool")
    if not CONVENTIONAL.match(subject):
        problems.append(
            f"{where}: subject is not a Conventional Commit "
            "(type(scope): lowercase imperative subject)"
        )
    if not ISSUE_REF.search(message):
        problems.append(f"{where}: message does not reference an issue")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--range", help="git rev range to check, e.g. base..head")
    parser.add_argument("--pr-body", help="path to a file holding the pull request body")
    args = parser.parse_args()

    problems = []

    if args.range:
        shas = commits_in_range(args.range)
        if not shas:
            print(f"No non-merge commits in {args.range}; nothing to check.")
        for sha in shas:
            check_commit(sha, problems)

    if args.pr_body:
        with open(args.pr_body, encoding="utf-8") as handle:
            body = handle.read()
        if TRAILER.search(body):
            problems.append("pull request body: carries an attribution trailer")
        if ATTRIBUTION.search(body):
            problems.append(
                "pull request body: attributes the work to an AI or generator tool"
            )

    if problems:
        print("Commit hygiene check FAILED:\n", file=sys.stderr)
        for problem in problems:
            print(f"  - {problem}", file=sys.stderr)
        print(
            "\nSee the Branches and Authorship rules in CLAUDE.md and Principle I of "
            ".specify/memory/constitution.md.",
            file=sys.stderr,
        )
        return 1

    print("Commit hygiene check passed.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
