#!/usr/bin/env python3
"""Tests for the commit hygiene checker.

Every case here corresponds to a defect found by adversarial review of the
first implementation. Run with: python3 scripts/test_check_commit_hygiene.py
"""
import importlib.util
import pathlib
import sys

spec = importlib.util.spec_from_file_location(
    "hygiene", pathlib.Path(__file__).parent / "check-commit-hygiene.py"
)
hygiene = importlib.util.module_from_spec(spec)
spec.loader.exec_module(hygiene)

FOOTER = "🤖 Generated with [Claude Code](https://claude.com/claude-code)"
TRAILER = "Co-Authored-By: Claude <noreply@anthropic.com>"

# (label, text, should_fail)
CASES = [
    # --- must FAIL: real attribution -------------------------------------
    ("canonical footer in prose", FOOTER, True),
    ("canonical footer inside a code fence", f"```\n{FOOTER}\n```", True),
    ("co-author trailer in prose", TRAILER, True),
    ("co-author trailer inside a code fence", f"```\n{TRAILER}\n```", True),
    ("signed-off-by carrying an AI identity", "Signed-off-by: Claude <noreply@anthropic.com>", True),
    ("unknown trailer key carrying an AI identity", "Helped-by: Claude <noreply@anthropic.com>", True),
    ("adverb between verb and preposition", "This was written entirely by Claude Code.", True),
    ("product name plus verb", "Claude Code wrote this migration.", True),
    ("copilot chat plus verb", "Copilot Chat generated the tests.", True),
    ("thanks to phrasing", "Thanks to Claude for the implementation.", True),
    ("help from phrasing", "Refactored the parser with help from Claude.", True),
    ("help of phrasing", "Refactored with the help of Claude.", True),
    ("ai-assisted claim", "This document was AI-assisted throughout.", True),
    ("zero-width space in a trailer", "Co-Authored-By:​ Claude <noreply@anthropic.com>", True),

    # --- must PASS: description, not attribution -------------------------
    ("naming the integration", "Spec Kit with the Claude Code integration.", False),
    ("naming the skills directory", "Skills live in .claude/skills/ in this repo.", False),
    ("describing that a review ran", "Round 2: 3 lenses, 29 agents, 13 findings refuted.", False),
    ("quoting a pattern as a code span", "The check rejects `written by Claude` in prose.", False),

    # --- must PASS: place names ending in 'ai' ---------------------------
    ("Mumbai", "fix(i18n): correct the format produced by the Mumbai locale", False),
    ("Thai", "docs(i18n): add copy made with Thai localisation", False),
    ("Sinai", "chore(assets): drop the icons created by Sinai Design", False),
    ("Dubai", "feat(map): render tiles generated by the Dubai extract", False),
]


def main():
    failures = []
    for label, text, should_fail in CASES:
        problems = hygiene.attribution_problems(text, "test")
        did_fail = bool(problems)
        if did_fail != should_fail:
            want = "FAIL" if should_fail else "PASS"
            got = "FAIL" if did_fail else "PASS"
            failures.append(f"{label}: expected {want}, got {got} ({problems})")

    # Issue references must need a linking keyword.
    issue_cases = [
        ("Closes #7", True), ("Refs #7", True), ("See #7", True),
        ("tweak the palette to #000000", False),
        ("https://example.com/guide#2-setup", False),
        ("no reference at all", False),
    ]
    for text, should_match in issue_cases:
        got = bool(hygiene.ISSUE_REF.search(text))
        if got != should_match:
            failures.append(f"issue ref {text!r}: expected {should_match}, got {got}")

    # The hook must ignore git's comment block and -v diff.
    hooked = hygiene.strip_git_comments(
        "feat(x): add thing\n\nCloses #1\n"
        "# Please enter the commit message. Generated with Claude Code.\n"
        "# ------------------------ >8 ------------------------\n"
        f"diff --git a/x b/x\n+{FOOTER}\n"
    )
    if hygiene.attribution_problems(hooked, "hook"):
        failures.append("hook: flagged text from git's comment block or diff")

    for failure in failures:
        print(f"FAIL  {failure}")
    total = len(CASES) + len(issue_cases) + 1
    print(f"\n{total - len(failures)}/{total} passed")
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main())
